defmodule FiveApps.Repo.Migrations.UpdateRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:weapons) do
      modify :range, :text, default: nil
    end

    alter table(:campaigns) do
      add :description, :text
      add :status, :text, default: "creating"
      add :story_points, :bigint, default: 0
      add :turn_number, :bigint, default: 0
      add :difficulty, :text, default: "normal"
      add :victory, :text
      add :notes, :text

      add :owner_id,
          references(:users,
            column: :id,
            name: "campaigns_owner_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:campaigns, "campaigns_owner_id_fkey")

    alter table(:campaigns) do
      remove :owner_id
      remove :notes
      remove :victory
      remove :difficulty
      remove :turn_number
      remove :story_points
      remove :status
      remove :description
    end

    alter table(:weapons) do
      modify :range, :text, default: "0"
    end
  end
end
