defmodule FiveApps.Repo.Migrations.AddingCrewMemberRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crew_members) do
      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "crew_members_campaign_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop constraint(:crew_members, "crew_members_campaign_id_fkey")

    alter table(:crew_members) do
      remove :campaign_id
    end
  end
end
