defmodule FiveApps.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crew_members) do
      modify :species, :text, null: false
    end
  end

  def down do
    alter table(:crew_members) do
      modify :species, :text, null: true
    end
  end
end
