defmodule FiveApps.Repo.Migrations.UpdatingShipAttributes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:ships) do
      modify :clock, :bigint, default: 0
      modify :event, :bigint, default: 0
      modify :debt, :bigint, default: 0
      modify :hull, :bigint, default: 0
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:ships) do
      modify :name, :text, null: true
      modify :hull, :bigint, default: nil
      modify :debt, :bigint, default: nil
      modify :event, :bigint, default: nil
      modify :clock, :bigint, default: nil
    end
  end
end
