defmodule FiveApps.Repo.Migrations.UpdatingShipRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
      add :hull, :bigint
      add :debt, :bigint
      add :traits, :text
      add :upgrades, :text
      add :story_tracks, :text
      add :event, :bigint
      add :clock, :bigint
      add :rumors, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "ships_campaign_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:campaigns) do
      remove :ship
    end
  end

  def down do
    alter table(:campaigns) do
      add :ship, :map
    end

    drop constraint(:ships, "ships_campaign_id_fkey")

    drop table(:ships)
  end
end
