defmodule FiveApps.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:weapons) do
      modify :range, :text, default: nil
    end
  end

  def down do
    alter table(:weapons) do
      modify :range, :text, default: "0"
    end
  end
end
