defmodule FiveApps.Repo.Migrations.AddingWeaponsToCrew do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:weapons, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :range, :text, default: "0"
      add :shot, :bigint, default: 0
      add :damage, :bigint, default: 0
      add :traits, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :crew_member_id,
          references(:crew_members,
            column: :id,
            name: "weapons_crew_member_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:crew_members) do
      modify :savvy, :bigint, default: 0
      modify :toughness, :bigint, default: 0
      modify :combat, :bigint, default: 0
      modify :speed, :bigint, default: 0
      modify :reactions, :bigint, default: 0
    end
  end

  def down do
    alter table(:crew_members) do
      modify :reactions, :bigint, default: nil
      modify :speed, :bigint, default: nil
      modify :combat, :bigint, default: nil
      modify :toughness, :bigint, default: nil
      modify :savvy, :bigint, default: nil
    end

    drop constraint(:weapons, "weapons_crew_member_id_fkey")

    drop table(:weapons)
  end
end
