defmodule FiveApps.Repo.Migrations.UpdatingStashRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stashes, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :notes, :text
      add :credits, :bigint, default: 0
      add :patrons, :bigint, default: 0
      add :rivals, :bigint, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :campaign_id,
          references(:campaigns,
            column: :id,
            name: "stashes_campaign_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:campaigns) do
      remove :stash
    end
  end

  def down do
    alter table(:campaigns) do
      add :stash, :map
    end

    drop constraint(:stashes, "stashes_campaign_id_fkey")

    drop table(:stashes)
  end
end
